markdown: rdiscount
pygments: true
plugins: ./_plugins
paginate: 8

safe: false
# 当修改文件时重新生成站点  
auto: true  

#站点基础配置
title: MmagicBox
subTitle: 移动魔盒工作室，专注于移动App开发
description: 这是 MmagicBox 的又一个博客，它是基于 Jekyll 搭建起来的。在这里，不仅仅是用来快速记录工作，学习，生活的一点一滴的地方，更是 MmagicBox 对 Jekyll 的学习和使用的一次有意义的实践。
url: http://mmagicbox.github.io
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 作品
    url: /works.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 工具
    url: /README.md

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-google-plus
    url: http://weibo.com/mmagicbox
  - class: fa-facebook
    url: http://weibo.com/mmagicbox
  - class: fa-github
    url: http://weibo.com/mmagicbox
  - class: fa-weibo
    url: http://weibo.com/mmagicbox
  - class: fa-renren
    url: http://weibo.com/mmagicbox
  - class: fa-pinterest
    url: http://weibo.com/mmagicbox
  - class: fa-twitter
    url: http://weibo.com/mmagicbox
  - class: fa-rss
    url: http://weibo.com/mmagicbox

#作者信息
author:
  link: http://mmagicbox.github.io/contact.html
  img: http://tp2.sinaimg.cn/1832671293/180/40020872447/1

#评论信息
disqus:
  config: true
  id: piznblog

duoshuo:
  config: false
  id: zhanxin